### ISSUE TITLE
Firing on a specific page/URL

### ISSUE THREAD

**Issue by jaykay1966** [EagerApps/Feedback#2]
Hi,
Is it possible to get this to fire on specific page or URL - e.g. after a checkout?
Cheers
Jay

**Comment by zackbloom** [comment]
Hi @jaykay1966,

One thing you could do is use the [Eager app](https://eager.io/app/feedback/install) to only install Feedback on a specific page, using [page selection](https://eager.io/blog/introducing-page-selection/).  If you want the dropdown to open automatically, you could use the [Add HTML](https://eager.io/app/add-html/install) app to add something like this to your page:

``` html
<script>
  if (window.EagerFeedbackApp && window.addEventListener){
    window.addEventListener('load', function(){
      window.EagerFeedbackApp.show();
    });
  }
</script>
```

**Comment by jaykay1966** [comment]
Thanks Zack. I will give that a try.
